name: Rust checks
on: [push, pull_request]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  checks:
    strategy:
      fail-fast: false
      matrix:
        directory: ["./rust-arkworks", "./rust-k256"]
        command: ["check", "clippy", "test"]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@nightly
        with:
          components: "clippy, rustfmt"

      - name: ${{ matrix.command }}
        run: |
          cargo build
          cargo ${{ matrix.command }} --all-features
        working-directory: ${{ matrix.directory }}
